Agent_settings:
  Output_csv: 'resultados un agente/pruebas/presion'
  Output_model: 'sin aprendizaje'
  Environment:
    Gui: False
    Num_seconds: 7200
    Min_green: 5
    Max_green: 60
    Yellow_time: 3
    Delta_time: 5
  Instances:
    SARSA_run_1:
      Agent_type: 'SARSA'
      Runs: 1
      Model: 'output\models\entrenamiento\presion\SARSA_run_1.pkl'
  
    